version: '3.8'

services:
  kromosynth-render:
    build:
      context: .
      dockerfile: render-socket/Dockerfile.flexible
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      # Choose which implementation to run: socket-server-pcm.js or socket-server-pcm-parallel.js
      - SERVER_IMPLEMENTATION=socket-server-pcm.js
    restart: unless-stopped
    networks:
      - kromosynth-network

  # Optional: Run both implementations side by side for testing
  kromosynth-render-parallel:
    build:
      context: .
      dockerfile: render-socket/Dockerfile.flexible
    ports:
      - "3001:3000"
    environment:
      - PORT=3000
      - SERVER_IMPLEMENTATION=socket-server-pcm-parallel.js
    restart: unless-stopped
    networks:
      - kromosynth-network

networks:
  kromosynth-network:
    driver: bridge
