version: '3.8'

services:
  kromosynth-render:
    build:
      context: ./render-socket
      dockerfile: Dockerfile.pcm
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - kromosynth-network
    # Uncomment for volume mounts if needed
    # volumes:
    #   - ./data:/app/data

  # Example second service - replace with your actual second server
  # second-service:
  #   image: your-second-service:latest
  #   ports:
  #     - "3001:3001"
  #   environment:
  #     - PORT=3001
  #     - NODE_ENV=production
  #   depends_on:
  #     - kromosynth-render
  #   restart: unless-stopped
  #   networks:
  #     - kromosynth-network

networks:
  kromosynth-network:
    driver: bridge
