version: '3.8'

# Example Docker Compose configuration that references the GitHub repository
# This can be used by other projects that want to include kromosynth-render as a service

services:
  kromosynth-render:
    build:
      context: https://github.com/synth-is/kromosynth-render.git
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - app-network

  # Your other services here
  # my-app:
  #   image: my-app:latest
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - kromosynth-render
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge
