version: '3'
services:
  envoy:
      platform: linux/amd64
      build:
        context: ./
        dockerfile: ./envoy/Dockerfile
      image: grpcweb/envoy
      ports:
        - "8080:8080"
      links:
        - node-server
  node-server:
    platform: linux/amd64
    build:
      context: ./
      dockerfile: ./node-server/Dockerfile
    image: bthj/kromosynth-render
    ports:
      - "9090:9090"