version: '3.8'

services:
  kromosynth-render:
    build:
      context: ./render-socket
      dockerfile: Dockerfile.pcm
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    restart: unless-stopped
    networks:
      - kromosynth-network

  # Example second service - replace with your actual second server
  # second-service:
  #   image: your-second-service:latest
  #   ports:
  #     - "3001:3001"
  #   environment:
  #     - PORT=3001
  #   depends_on:
  #     - kromosynth-render
  #   networks:
  #     - kromosynth-network

networks:
  kromosynth-network:
    driver: bridge
