version: '3'
services:
  envoy:
      build:
        context: ./
        dockerfile: ./net/grpc/gateway/docker/envoy/Dockerfile
      image: grpcweb/envoy
      ports:
        - "8080:8080"
      links:
        - node-server
  node-server:
    build:
      context: ./
      dockerfile: ./node-server/Dockerfile
    depends_on:
      - prereqs
    image: bthj/kromosynth-render
    ports:
      - "9090:9090"