---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "kromosynth-render-service"
  namespace: "bthj-ns0000k"
  labels:
    app: "kromosynth-render"
spec:
  ports:
    - name: grpc-proxy
      protocol: "TCP"
      port: 80
      targetPort: 8080
    - name: grpc
      protocol: "TCP"
      port: 9090
      targetPort: 9090
  selector:
    app: "kromosynth-render"
  type: "LoadBalancer"